#ifndef ULTRASONIC_CONFIG_H
#define ULTRASONIC_CONFIG_H

#include "../../MCAL/GPIO/GPIO_interface.h"

/* Sensor IDs */
#define ULTRASONIC_FRONT    0u
#define ULTRASONIC_BACK     1u
#define ULTRASONIC_LEFT     2u
#define ULTRASONIC_RIGHT    3u
#define ULTRASONIC_EXTRA    4u

/* Front - RB1 TRIG, RB2 ECHO. RB0 stays reserved for firmware signature LED. */
#define ULTRASONIC_FRONT_TRIG_PORT  GPIO_PORTB
#define ULTRASONIC_FRONT_TRIG_PIN   GPIO_PIN1
#define ULTRASONIC_FRONT_ECHO_PORT  GPIO_PORTB
#define ULTRASONIC_FRONT_ECHO_PIN   GPIO_PIN2

/* Back - RB3 TRIG, RB4 ECHO */
#define ULTRASONIC_BACK_TRIG_PORT   GPIO_PORTB
#define ULTRASONIC_BACK_TRIG_PIN    GPIO_PIN3
#define ULTRASONIC_BACK_ECHO_PORT   GPIO_PORTB
#define ULTRASONIC_BACK_ECHO_PIN    GPIO_PIN4

/* Left - reserved for later */
#define ULTRASONIC_LEFT_TRIG_PORT   GPIO_PORTB
#define ULTRASONIC_LEFT_TRIG_PIN    GPIO_PIN5
#define ULTRASONIC_LEFT_ECHO_PORT   GPIO_PORTB
#define ULTRASONIC_LEFT_ECHO_PIN    GPIO_PIN6

/* Right - reserved for later */
#define ULTRASONIC_RIGHT_TRIG_PORT  GPIO_PORTD
#define ULTRASONIC_RIGHT_TRIG_PIN   GPIO_PIN4
#define ULTRASONIC_RIGHT_ECHO_PORT  GPIO_PORTD
#define ULTRASONIC_RIGHT_ECHO_PIN   GPIO_PIN5

/* Extra sensor - reserved for later */
#define ULTRASONIC_EXTRA_TRIG_PORT  GPIO_PORTD
#define ULTRASONIC_EXTRA_TRIG_PIN   GPIO_PIN6
#define ULTRASONIC_EXTRA_ECHO_PORT  GPIO_PORTD
#define ULTRASONIC_EXTRA_ECHO_PIN   GPIO_PIN7

/* Stop distance threshold (cm) */
#define ULTRASONIC_STOP_THRESHOLD   20u

#endif
