#ifndef ULTRASONIC_CONFIG_H
#define ULTRASONIC_CONFIG_H

#include "../../MCAL/GPIO/GPIO_interface.h"

/* Sensor IDs */
#define ULTRASONIC_FRONT    0u
#define ULTRASONIC_BACK     1u
#define ULTRASONIC_LEFT     2u
#define ULTRASONIC_RIGHT    3u

/* Front — RB0 TRIG, RB1 ECHO */
#define ULTRASONIC_FRONT_TRIG_PORT  GPIO_PORTB
#define ULTRASONIC_FRONT_TRIG_PIN   GPIO_PIN0
#define ULTRASONIC_FRONT_ECHO_PORT  GPIO_PORTB
#define ULTRASONIC_FRONT_ECHO_PIN   GPIO_PIN1

/* Back — RB2 TRIG, RB3 ECHO */
#define ULTRASONIC_BACK_TRIG_PORT   GPIO_PORTB
#define ULTRASONIC_BACK_TRIG_PIN    GPIO_PIN2
#define ULTRASONIC_BACK_ECHO_PORT   GPIO_PORTB
#define ULTRASONIC_BACK_ECHO_PIN    GPIO_PIN3

/* Left — RB4 TRIG, RB5 ECHO */
#define ULTRASONIC_LEFT_TRIG_PORT   GPIO_PORTB
#define ULTRASONIC_LEFT_TRIG_PIN    GPIO_PIN4
#define ULTRASONIC_LEFT_ECHO_PORT   GPIO_PORTB
#define ULTRASONIC_LEFT_ECHO_PIN    GPIO_PIN5

/* Right — RB6 TRIG, RB7 ECHO */
#define ULTRASONIC_RIGHT_TRIG_PORT  GPIO_PORTB
#define ULTRASONIC_RIGHT_TRIG_PIN   GPIO_PIN6
#define ULTRASONIC_RIGHT_ECHO_PORT  GPIO_PORTB
#define ULTRASONIC_RIGHT_ECHO_PIN   GPIO_PIN7

/* Stop distance threshold (cm) */
#define ULTRASONIC_STOP_THRESHOLD   20u

#endif
