#ifndef ULTRASONIC_CONFIG_H
#define ULTRASONIC_CONFIG_H

#include "../../MCAL/GPIO/GPIO_interface.h"

/* Sensor IDs */
#define ULTRASONIC_FRONT    0u
#define ULTRASONIC_BACK     1u
#define ULTRASONIC_LEFT     2u
#define ULTRASONIC_RIGHT    3u
#define ULTRASONIC_EXTRA    4u

/* Front - RB1 TRIG, RB2 ECHO. RB0 stays reserved for firmware signature LED. */
#define ULTRASONIC_FRONT_TRIG_PORT  GPIO_PORTB
#define ULTRASONIC_FRONT_TRIG_PIN   GPIO_PIN1
#define ULTRASONIC_FRONT_ECHO_PORT  GPIO_PORTB
#define ULTRASONIC_FRONT_ECHO_PIN   GPIO_PIN2

/* Back - reserved for later; the final demo uses front/left/right. */
#define ULTRASONIC_BACK_TRIG_PORT   GPIO_PORTD
#define ULTRASONIC_BACK_TRIG_PIN    GPIO_PIN6
#define ULTRASONIC_BACK_ECHO_PORT   GPIO_PORTD
#define ULTRASONIC_BACK_ECHO_PIN    GPIO_PIN7

/* Left - RB3 TRIG, RB4 ECHO */
#define ULTRASONIC_LEFT_TRIG_PORT   GPIO_PORTB
#define ULTRASONIC_LEFT_TRIG_PIN    GPIO_PIN3
#define ULTRASONIC_LEFT_ECHO_PORT   GPIO_PORTB
#define ULTRASONIC_LEFT_ECHO_PIN    GPIO_PIN4

/* Right - RB5 TRIG, RB6 ECHO */
#define ULTRASONIC_RIGHT_TRIG_PORT  GPIO_PORTB
#define ULTRASONIC_RIGHT_TRIG_PIN   GPIO_PIN5
#define ULTRASONIC_RIGHT_ECHO_PORT  GPIO_PORTB
#define ULTRASONIC_RIGHT_ECHO_PIN   GPIO_PIN6

/* Extra sensor - reserved for later */
#define ULTRASONIC_EXTRA_TRIG_PORT  GPIO_PORTD
#define ULTRASONIC_EXTRA_TRIG_PIN   GPIO_PIN6
#define ULTRASONIC_EXTRA_ECHO_PORT  GPIO_PORTD
#define ULTRASONIC_EXTRA_ECHO_PIN   GPIO_PIN7

/* Measurement/filter policy used by the active car application. */
#define ULTRASONIC_SAMPLE_COUNT       3U
#define ULTRASONIC_MIN_VALID          2U
#define ULTRASONIC_MAX_VALID_CM       400U
#define ULTRASONIC_INTER_PING_MS      60U
#define ULTRASONIC_OBSTACLE_BLOCK_CM  50U

/* Compatibility name used by older obstacle test code. */
#define ULTRASONIC_STOP_THRESHOLD     ULTRASONIC_OBSTACLE_BLOCK_CM

#endif
